name: cloudmonkey
# define the tag anchor on the allowed 'version' field
version: &release_tag 6.4.0
summary: Apache CloudStack CLI
description: |
  A CLI and interactive shell that simplifies configuration and management of
  Apache CloudStack, the opensource IAAS cloud computing platform.

base: core22
license: Apache-2.0
grade: stable
confinement: strict
adopt-info: cloudmonkey

apps:
  cloudmonkey:
    command: bin/cmk
    plugs: [home, network]

parts:
  cloudmonkey:
    plugin: go
    source: &cmk_repo https://github.com/apache/cloudstack-cloudmonkey.git
    source-type: git
    source-tag: *release_tag
    source-depth: 1

    build-snaps: [go]
    build-packages: [git, file, binutils]

    build-environment:
      - CMK_REPO: *cmk_repo
      - CMK_TAG:  *release_tag

    override-pull: |
      set -euo pipefail
      craftctl default
      REPO="${CMK_REPO}"
      TAG="${CMK_TAG}"
      FULL_SHA="$(git ls-remote "${REPO}" "refs/tags/${TAG}" | awk '{print $1}')"
      SHORT_SHA="${FULL_SHA:0:7}"
      : "${SHORT_SHA:=unknown}"
      echo "${SHORT_SHA}" > "$CRAFT_PART_SRC/.remote-sha"
      craftctl set version="${TAG}-${SHORT_SHA}"

    override-build: |
      set -euo pipefail
      cd "$CRAFT_PART_SRC"
      SHORT_SHA="$(cat .remote-sha 2>/dev/null || echo unknown)"
      BUILD_DATE="$(date +%FT%T%z)"
      go mod vendor || true
      go build -trimpath \
        -ldflags "-s -w -X main.GitSHA=${SHORT_SHA} -X main.BuildDate=${BUILD_DATE}" \
        -o cmk cmk.go
      install -Dm0755 cmk "$CRAFT_PART_INSTALL/bin/cmk"
      strip --remove-section=.comment --remove-section=.note "$CRAFT_PART_INSTALL/bin/cmk" || true
